# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7eaec52f13219b348eb205f80bf5f7d7638e8da61c6ec68ca1d8aa23ef0e3f6a24bd194d8a7b08e40baf09dfab381cea344ca94540b4dc2b7f878b2b99193bf

test:
  secret_key_base: 99d107d7ab57379bd882977bc5bdebf2e9e0cfb94235b93525800b9e5b4168579f1dbd228f04c7b28b57e850a396436ab29baee50d80937cb86ddb6bc792db34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
